apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      service: {{ template "trackableappname" . }}
  replicas: {{ if eq .Values.release_mode "production" }} {{ .Values.deployment.replicas.prod }} {{ else }} {{ .Values.deployment.replicas.dev }} {{ end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "trackableappname" . }}
        service: {{ template "trackableappname" . }}
      annotations:
        git_commit: {{ .Values.git.commit }}
        app.gitlab.com/app: {{ .Values.git.path }}
        app.gitlab.com/env: {{ .Values.git.branch }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.registry.secret }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.registry.image }}
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.internalPort }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}



